# Generated by Django 5.1.3 on 2025-02-05 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('friend_id', models.AutoField(primary_key=True, serialize=False)),
                ('friend_status', models.BooleanField()),
                ('blocked', models.BooleanField()),
                ('pending', models.BooleanField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friends',
            },
        ),
    ]
